import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useMemo } from "react";
import { embedSteganography, detectSteganography } from "../lib/steganography";

const Home: NextPage = () => {
  const [text, setText] = React.useState("");
  const [hiddenText, setHiddenText] = React.useState("");
  const [decodeText, setDecodeText] = React.useState("");
  const embedded = useMemo(
    () => embedSteganography(text, hiddenText),
    [text, hiddenText]
  );
  const detected = useMemo(() => detectSteganography(decodeText), [decodeText]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>秘密のメッセージ</h1>

        <div>
          <p>作成</p>
          <div>
            <p>text</p>
            <input onChange={(e) => setText(e.target.value)} value={text} />
          </div>

          <div>
            <p>secret</p>
            <input
              onChange={(e) => setHiddenText(e.target.value)}
              value={hiddenText}
            />
          </div>

          <div>
            <p>embedded</p>
            <input value={embedded} readOnly={true} />
            <p>copy this text area</p>
          </div>
        </div>

        <div>
          <div>
            <p>検出</p>
            <div>
              <p>message</p>
              <input
                value={decodeText}
                onChange={(e) => {
                  setDecodeText(e.target.value);
                }}
              />
            </div>
            <div>
              <p>hidden</p>
              <input value={detected[0] || ""} readOnly={true} />
            </div>
          </div>
        </div>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
